### ISSUE TITLE
close all open modal

### ISSUE THREAD

**Issue by miinoru** [GedMarc/Bootstrap-Dialog4#1]
thanks for your work on updating the plugin!!
I only have the problem, which I do not achieve. close all open modal. 

```
                $.each(BootstrapDialog.dialogs, function(id, dialog){
                    dialog.close();
                });
```
How is this achieved? in advance thank you very much and apologize for the bad english :P

**Comment by GedMarc** [comment]
You can use  $('.modal').modal('hide');
